export const DEFAULT_TICKERS = [
  'ITBEES.NS', 'BANKBEES.NS', 'NIFTYBEES.NS', 'JUNIORBEES.NS',
  'ALPHA.NS', 'MOMENTUM.NS', 'GOLDBEES.NS', 'SILVERBEES.NS',
  'PHARMABEES.NS', 'FMCGIETF.NS', 'MIDCAP.NS', 'EVINDIA.NS',
  'MODEFENCE.NS', 'PSUBNKBEES.NS', 'BTC-USD', 'ETH-USD'
];